# Generated by Django 6.0 on 2026-01-01 06:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('progress', models.FloatField(default=0.0)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolution', models.CharField(default='1080', max_length=10)),
                ('is_audio', models.BooleanField(default=False)),
            ],
        ),
    ]
