# Generated by Django 6.0 on 2026-01-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadtask',
            name='is_audio',
        ),
        migrations.AddField(
            model_name='downloadtask',
            name='audio_format',
            field=models.CharField(default='mp3', max_length=10),
        ),
        migrations.AddField(
            model_name='downloadtask',
            name='audio_quality',
            field=models.CharField(default='best', max_length=10),
        ),
        migrations.AddField(
            model_name='downloadtask',
            name='container',
            field=models.CharField(default='mp4', max_length=10),
        ),
        migrations.AddField(
            model_name='downloadtask',
            name='task_type',
            field=models.CharField(default='video', max_length=10),
        ),
        migrations.AddField(
            model_name='downloadtask',
            name='use_subtitle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='downloadtask',
            name='use_thumbnail',
            field=models.BooleanField(default=False),
        ),
    ]
